### ISSUE TITLE
Peer Review - Week 2

### ISSUE THREAD

**Issue by kilroy763** [joordy/i-call#11]
* Documenten goed duidelijk opgesteld en goed gemoduleerd.
* Voeg in de Readme een beschrijving toe van je project, wat je gaat maken.
* Data Flow Diagram ziet er goed uit, vergeet niet de features in je readme aan te vullen.

* De site ziet er goed uit, css moet nog toegepast worden op het eerste formulier. 
* Laat duidelijker zien dat de camera uit staat (op de knop) en dat de micrfoon gemute is, zodra je erop drukt.
* Voeg wat meer margin toe tussen de camera's in, ze zijn nu op elkaar geplakt.

* Data Flow diagram ziet er erg goed uit, netjes onderscheiden betreft client / server.

* Voeg nog een kopje toe in de readme die aantoont wat de API doet en welke API je gebruikt. Is voor nu nog onduidelijk.

**Comment by joordy** [comment]
Thanks for the feedback! I converted in tasks on my project bord. You can track the progress here: [Project board](https://github.com/joordy/i-call/projects/1)
