### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by tsjuusmei** [joordy/i-call#12]
Ik mis een uitleg van welk concept je gaat uitwerken. Livelink is aanwezig en er zijn geen onnodige files (voor zover ik zie) in de repo.

De livelink lijkt helemaal prima te werken! Het ziet er ook al nice uit. Het enige wat niet werkte bij mij was de leave button.

Data flow is aanwezig en duidelijk. Ik mis nog wel de uitleg van de API, maar volgens mij is deze er ook nog niet helemaal in verwerkt.

**Comment by joordy** [comment]
Thanks for the feedback! I converted in tasks on my project bord. You can track the progress here: [Project board](https://github.com/joordy/i-call/projects/1)
