### ISSUE TITLE
Peer feedback W2

### ISSUE THREAD

**Issue by lars-ruijs** [joordy/i-call#13]
## Repository
- [ ] Er is nog geen project beschrijving toegevoegd van wat je hebt gemaakt
- [ ] Je lijst met features kan nog worden uitgebreid
- [ ] De data die de API terugstuurt is nog niet inzichtelijk
- [X] Er staan geen bestanden in je repo die er niet horen
- [X] Er is een live link toegevoegd 

## Concept
- [ ] Ik weet welk concept je hebt gekozen, maar dat staat nu nog niet in je readme
- [ ] Er ontbreekt nog een schets van het concept dat je nu hebt gekozen
- [ ] Als ik een room join vanaf een link, kan ik me naam niet invullen
- [ ] Ik weet nog niet hoe je nu een random katten feitje kunt krijgen 😺
- [X] Het bellen met mezelf in een ander tabblad werkt goed, ik zie mezelf twee keer en hoor mezelf twee keer
- [X] App interface voor het bellen ziet er al goed uit

## Data life cycle
- [ ] Mis nog een overzicht van de data die door de server of een database wordt bijgehouden
- [ ] Het disconnect event is nog niet getoond in de diagram
- [X] Goed overzicht van hoe events door je app heen gaan
- [X] De verbinding met de API is duidelijk zichtbaar in de diagram

## Real-time events
- [X] Alle custom events zijn beschreven
- [X] Communicatie tussen client en server is duidelijk

## API 
- [ ] Beschrijving van API ontbreekt
- [ ] Niet duidelijk welke data je terug krijgt en hoe je een API key  krijgt.

**Comment by joordy** [comment]
Thanks for the feedback! I converted in tasks on my project bord. You can track the progress here: [Project board](https://github.com/joordy/i-call/projects/1)
